"""baseline schema

Revision ID: f3296f59455b
Revises: 
Create Date: 2026-09-28 10:21:37.609480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3296f59455b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autosar_mechanisms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.Enum('SOFTWARE_CHANGE', 'AUTOSAR_CONFIG_CHANGE', 'ECU_CHANGE', 'NETWORK_MESSAGE_CHANGE', 'CRYPTO_LIBRARY_CHANGE', 'REQUIREMENT_CHANGE', 'TARA_CHANGE', 'VULNERABILITY', 'SBOM_CHANGE', name='changetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.Column('impact_level', sa.String(length=20), nullable=True),
    sa.Column('impact_report', sa.JSON(), nullable=False),
    sa.Column('impact_summary', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('security_assessment', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_entity', sa.String(length=80), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('standard', sa.String(length=120), nullable=False),
    sa.Column('control_id', sa.String(length=80), nullable=False),
    sa.Column('target_entity', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('mapping_type', sa.String(length=60), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['standard_id'], ['standards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_standard_id'), 'controls', ['standard_id'], unique=False)
    op.create_table('ecus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ecu_type', sa.String(length=120), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('hardware_version', sa.String(length=80), nullable=False),
    sa.Column('software_version', sa.String(length=80), nullable=False),
    sa.Column('criticality', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecus_vehicle_id'), 'ecus', ['vehicle_id'], unique=False)
    op.create_table('networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('network_type', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ecu_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_networks_vehicle_id'), 'networks', ['vehicle_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_organization_id'), 'suppliers', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CYBERSECURITY_ENGINEER', 'ARCHITECT', 'TESTER', 'SUPPLIER', 'AUDITOR', 'VIEWER', name='role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('criticality', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ecu_id'], ['ecus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_ecu_id'), 'assets', ['ecu_id'], unique=False)
    op.create_table('mechanism_implementations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mechanism_id', sa.Integer(), nullable=False),
    sa.Column('ecu_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['ecu_id'], ['ecus.id'], ),
    sa.ForeignKeyConstraint(['mechanism_id'], ['autosar_mechanisms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mechanism_id', 'ecu_id', name='uq_mech_ecu')
    )
    op.create_index(op.f('ix_mechanism_implementations_ecu_id'), 'mechanism_implementations', ['ecu_id'], unique=False)
    op.create_index(op.f('ix_mechanism_implementations_mechanism_id'), 'mechanism_implementations', ['mechanism_id'], unique=False)
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecu_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('release_type', sa.String(length=60), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('gate_result', sa.String(length=20), nullable=True),
    sa.Column('gate_reasons', sa.JSON(), nullable=False),
    sa.Column('gate_evaluated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ecu_id'], ['ecus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_releases_ecu_id'), 'releases', ['ecu_id'], unique=False)
    op.create_table('sboms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('ecu_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=30), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('component_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ecu_id'], ['ecus.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sboms_ecu_id'), 'sboms', ['ecu_id'], unique=False)
    op.create_index(op.f('ix_sboms_vehicle_id'), 'sboms', ['vehicle_id'], unique=False)
    op.create_table('software_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=False),
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['ecu_id'], ['ecus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_components_ecu_id'), 'software_components', ['ecu_id'], unique=False)
    op.create_table('supplier_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', name='submissionstatus'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_submissions_supplier_id'), 'supplier_submissions', ['supplier_id'], unique=False)
    op.create_table('sbom_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbom_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=False),
    sa.Column('purl', sa.String(length=500), nullable=False),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('hash', sa.String(length=255), nullable=False),
    sa.Column('component_type', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['sbom_id'], ['sboms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sbom_components_sbom_id'), 'sbom_components', ['sbom_id'], unique=False)
    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('threat_type', sa.String(length=120), nullable=False),
    sa.Column('attack_vector', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threats_asset_id'), 'threats', ['asset_id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=40), nullable=False),
    sa.Column('cvss_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['software_components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_component_id'), 'vulnerabilities', ['component_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_table('taras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=False),
    sa.Column('damage_scenario', sa.Text(), nullable=False),
    sa.Column('threat_scenario', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=40), nullable=False),
    sa.Column('impact_level', sa.Integer(), nullable=False),
    sa.Column('attack_feasibility', sa.String(length=40), nullable=False),
    sa.Column('feasibility_level', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('cybersecurity_goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_taras_asset_id'), 'taras', ['asset_id'], unique=False)
    op.create_index(op.f('ix_taras_threat_id'), 'taras', ['threat_id'], unique=False)
    op.create_table('cybersecurity_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tara_id', sa.Integer(), nullable=True),
    sa.Column('requirement_id', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['tara_id'], ['taras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id')
    )
    op.create_index(op.f('ix_cybersecurity_requirements_tara_id'), 'cybersecurity_requirements', ['tara_id'], unique=False)
    op.create_table('requirement_control_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['cybersecurity_requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'control_id', name='uq_req_ctl')
    )
    op.create_index(op.f('ix_requirement_control_links_control_id'), 'requirement_control_links', ['control_id'], unique=False)
    op.create_index(op.f('ix_requirement_control_links_requirement_id'), 'requirement_control_links', ['requirement_id'], unique=False)
    op.create_table('requirement_mechanism_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('mechanism_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mechanism_id'], ['autosar_mechanisms.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['cybersecurity_requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'mechanism_id', name='uq_req_mech')
    )
    op.create_index(op.f('ix_requirement_mechanism_links_mechanism_id'), 'requirement_mechanism_links', ['mechanism_id'], unique=False)
    op.create_index(op.f('ix_requirement_mechanism_links_requirement_id'), 'requirement_mechanism_links', ['requirement_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('test_type', sa.String(length=80), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['cybersecurity_requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cases_requirement_id'), 'test_cases', ['requirement_id'], unique=False)
    op.create_table('control_test_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'test_case_id', name='uq_ctl_test')
    )
    op.create_index(op.f('ix_control_test_links_control_id'), 'control_test_links', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_test_links_test_case_id'), 'control_test_links', ['test_case_id'], unique=False)
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('NOT_RUN', 'PASSED', 'FAILED', 'BLOCKED', name='teststatus'), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('tester', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_results_test_case_id'), 'test_results', ['test_case_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_reference', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('MISSING', 'DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='evidencestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.Column('test_result_id', sa.Integer(), nullable=True),
    sa.Column('release_id', sa.Integer(), nullable=True),
    sa.Column('tara_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['cybersecurity_requirements.id'], ),
    sa.ForeignKeyConstraint(['tara_id'], ['taras.id'], ),
    sa.ForeignKeyConstraint(['test_result_id'], ['test_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_release_id'), 'evidences', ['release_id'], unique=False)
    op.create_index(op.f('ix_evidences_requirement_id'), 'evidences', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_evidences_tara_id'), 'evidences', ['tara_id'], unique=False)
    op.create_index(op.f('ix_evidences_test_result_id'), 'evidences', ['test_result_id'], unique=False)
    op.create_table('control_evidence_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('control_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'evidence_id', name='uq_ctl_ev')
    )
    op.create_index(op.f('ix_control_evidence_links_control_id'), 'control_evidence_links', ['control_id'], unique=False)
    op.create_index(op.f('ix_control_evidence_links_evidence_id'), 'control_evidence_links', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_evidence_links_evidence_id'), table_name='control_evidence_links')
    op.drop_index(op.f('ix_control_evidence_links_control_id'), table_name='control_evidence_links')
    op.drop_table('control_evidence_links')
    op.drop_index(op.f('ix_evidences_test_result_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_tara_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_requirement_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_release_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_test_results_test_case_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index(op.f('ix_control_test_links_test_case_id'), table_name='control_test_links')
    op.drop_index(op.f('ix_control_test_links_control_id'), table_name='control_test_links')
    op.drop_table('control_test_links')
    op.drop_index(op.f('ix_test_cases_requirement_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_requirement_mechanism_links_requirement_id'), table_name='requirement_mechanism_links')
    op.drop_index(op.f('ix_requirement_mechanism_links_mechanism_id'), table_name='requirement_mechanism_links')
    op.drop_table('requirement_mechanism_links')
    op.drop_index(op.f('ix_requirement_control_links_requirement_id'), table_name='requirement_control_links')
    op.drop_index(op.f('ix_requirement_control_links_control_id'), table_name='requirement_control_links')
    op.drop_table('requirement_control_links')
    op.drop_index(op.f('ix_cybersecurity_requirements_tara_id'), table_name='cybersecurity_requirements')
    op.drop_table('cybersecurity_requirements')
    op.drop_index(op.f('ix_taras_threat_id'), table_name='taras')
    op.drop_index(op.f('ix_taras_asset_id'), table_name='taras')
    op.drop_table('taras')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_component_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_threats_asset_id'), table_name='threats')
    op.drop_table('threats')
    op.drop_index(op.f('ix_sbom_components_sbom_id'), table_name='sbom_components')
    op.drop_table('sbom_components')
    op.drop_index(op.f('ix_supplier_submissions_supplier_id'), table_name='supplier_submissions')
    op.drop_table('supplier_submissions')
    op.drop_index(op.f('ix_software_components_ecu_id'), table_name='software_components')
    op.drop_table('software_components')
    op.drop_index(op.f('ix_sboms_vehicle_id'), table_name='sboms')
    op.drop_index(op.f('ix_sboms_ecu_id'), table_name='sboms')
    op.drop_table('sboms')
    op.drop_index(op.f('ix_releases_ecu_id'), table_name='releases')
    op.drop_table('releases')
    op.drop_index(op.f('ix_mechanism_implementations_mechanism_id'), table_name='mechanism_implementations')
    op.drop_index(op.f('ix_mechanism_implementations_ecu_id'), table_name='mechanism_implementations')
    op.drop_table('mechanism_implementations')
    op.drop_index(op.f('ix_assets_ecu_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_organization_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_networks_vehicle_id'), table_name='networks')
    op.drop_table('networks')
    op.drop_index(op.f('ix_ecus_vehicle_id'), table_name='ecus')
    op.drop_table('ecus')
    op.drop_index(op.f('ix_controls_standard_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_table('vehicles')
    op.drop_table('standards')
    op.drop_table('organizations')
    op.drop_table('compliance_mappings')
    op.drop_table('changes')
    op.drop_table('autosar_mechanisms')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
